In [1]:
                        ##-- Final model & predictions --##
# Importing libraries

import pandas as pd
import getpass
import math
import numpy as np
#from tqdm import trange
import gc
#import matplotlib.pyplot as plt
#import seaborn as sns
#from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import f1_score

if getpass.getuser() == "asus":
    file_path = "C:/Users/asus/Desktop/trendyol_data_v2/"
    
if getpass.getuser() == "your computers name":
    file_path = "C:/Users/..desiredlocation..."

In [2]:
test_joined_final = pd.read_csv(file_path + 'test_joined_final.csv')

In [3]:
data = pd.read_csv(file_path + 'main_data_without_ids.csv')

In [4]:
test_joined_final.head(2)

,user_id,product_content_id,order_parent_id,is_returned,Bay,Bayan,discounted_price,ship_cost,coupon_used,is_discounted,promotion_percent,is_shipcost_incurred,shipping_percent,return_prob_from_answers,return_prob_from_reviews,overall_return_prob_product
0,18115,87073974,726348863,will_be_predicted,0,1,72.126503,3.330133,0.211765,0.864706,0.202666,1.0,0.048002,0.0,0.038251,0.032484
1,27588,118753298,723169934,will_be_predicted,0,1,89.922159,4.446509,0.159091,0.886364,0.214756,1.0,0.049145,0.0,0.147989,0.020519

In [5]:
data.head(2)

,is_elite_user,discounted_price,ship_cost,is_wallet_trx,is_saved_card_trx,coupon_used,is_different_sizes,is_discounted,promotion_percent,is_shipcost_incurred,...,Siyah,Turkuaz,Turuncu,Yeşil,return_prob_from_answers,return_prob_from_reviews,Bay,Bayan,overall_return_prob_product,is_returned
0,0,51.94,8.88,0,1,0,0,1,0.349937,1,...,0,0,0,0,0.0,0.000000,0,1,0.025306,0.0
1,0,59.97,9.40,0,1,0,0,1,0.538515,1,...,0,0,0,1,0.0,0.047619,0,1,0.012821,0.0

In [6]:
data2 = data[['Bay','Bayan','discounted_price','ship_cost','coupon_used','is_discounted','promotion_percent',
             'is_shipcost_incurred','shipping_percent','return_prob_from_answers','return_prob_from_reviews',
             'overall_return_prob_product','is_returned']]

In [7]:
data2

,Bay,Bayan,discounted_price,ship_cost,coupon_used,is_discounted,promotion_percent,is_shipcost_incurred,shipping_percent,return_prob_from_answers,return_prob_from_reviews,overall_return_prob_product,is_returned
0,0,1,51.94,8.880,0,1,0.349937,1,0.170966,0.0,0.000000,0.025306,0.0
1,0,1,59.97,9.400,0,1,0.538515,1,0.156745,0.0,0.047619,0.012821,0.0
2,0,1,49.99,10.670,0,1,0.166694,1,0.213443,0.0,0.000000,0.273525,0.0
3,0,1,49.90,10.670,0,0,0.000000,1,0.213828,0.0,0.000000,0.027232,0.0
4,0,1,71.99,9.400,0,1,0.200022,1,0.130574,0.0,0.083333,0.032484,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10772617,0,1,71.99,11.330,0,1,0.640032,1,0.157383,0.0,0.040650,0.010932,0.0
10772618,0,1,85.58,2.098,0,1,0.643342,1,0.024515,0.0,0.037037,0.012821,0.0
10772619,0,1,75.98,2.098,0,1,0.650038,1,0.027613,0.0,0.000000,0.012821,0.0
10772620,0,1,69.73,10.490,0,1,0.650038,1,0.150437,0.0,0.000000,0.016131,0.0
10772621,0,1,75.98,2.098,0,1,0.650038,1,0.027613,0.0,0.000000,0.012821,0.0

In [8]:
del data

In [134]:
data2.is_returned.sum()/len(data2)

0.12720533589686894

In [136]:
gc.collect()

22

In [11]:
len(test_joined_final.drop_duplicates())

7471

In [12]:
#Constructing the model.
X = data2.iloc[:, :-1].values
y = data2.iloc[:, -1].values

In [15]:
gc.collect()

22

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 41)

In [14]:
gc.collect()

88

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
gc.collect()

22

In [18]:
classifier = RandomForestClassifier(n_estimators = 5, criterion = 'entropy', random_state = 41)
classifier.fit(X_train, y_train)
#took 15 minutes to train the model.

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=41)

In [137]:
gc.collect()

22

In [55]:
y_pred_test = classifier.predict(X_test)
print(np.concatenate((y_pred_test.reshape(len(y_pred_test),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 1.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 1.]
 [0. 1.]]

I don't expect 85% accuracy like before because I had to drop very important \
columns, which possibly constitute a ground for the predictive power \
of the random forest model.

Let's see what the new model gives us.

In [153]:
f1_score(y_test, y_pred_test, average='micro')

0.8551996245297339

## VERY INTERESTING.

In [25]:
test_joined_final_without_ids = test_joined_final.drop(['user_id','product_content_id','order_parent_id'],axis=1)

In [26]:
test_joined_final_without_ids

,is_returned,Bay,Bayan,discounted_price,ship_cost,coupon_used,is_discounted,promotion_percent,is_shipcost_incurred,shipping_percent,return_prob_from_answers,return_prob_from_reviews,overall_return_prob_product
0,will_be_predicted,0,1,72.126503,3.330133,0.211765,0.864706,0.202666,1.000000,0.048002,0.0,0.038251,0.032484
1,will_be_predicted,0,1,89.922159,4.446509,0.159091,0.886364,0.214756,1.000000,0.049145,0.0,0.147989,0.020519
2,will_be_predicted,0,1,79.813529,4.327934,0.218487,0.731092,0.202961,0.991597,0.055154,0.0,0.079365,0.014656
3,will_be_predicted,0,1,54.640780,3.002397,0.159696,0.787072,0.149364,1.000000,0.057721,0.0,0.104369,0.032484
4,will_be_predicted,0,1,65.268633,2.992710,0.173585,0.792453,0.149895,1.000000,0.048013,0.0,0.104167,0.032484
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7466,will_be_predicted,0,0,142.164107,4.872519,0.098214,0.767857,0.148564,1.000000,0.033868,0.0,0.159091,0.032484
7467,will_be_predicted,0,0,109.249958,2.739447,0.125000,0.663136,0.119912,1.000000,0.026313,0.0,0.128008,0.032484
7468,will_be_predicted,0,1,146.338667,7.691000,0.266667,1.000000,0.332255,1.000000,0.050333,0.0,0.091743,0.560377
7469,will_be_predicted,0,1,32.243333,3.090134,0.303704,0.807407,0.193715,0.992593,0.096521,0.0,0.038961,0.032484
7470,will_be_predicted,0,1,72.126503,3.330133,0.211765,0.864706,0.202666,1.000000,0.048002,0.0,0.038251,0.032484

## Prediction time

In [27]:
shiftpos = test_joined_final_without_ids.pop('is_returned')

In [28]:
test_joined_final_without_ids.insert(12, "is_returned", shiftpos)

In [29]:
test_joined_final_without_ids

,Bay,Bayan,discounted_price,ship_cost,coupon_used,is_discounted,promotion_percent,is_shipcost_incurred,shipping_percent,return_prob_from_answers,return_prob_from_reviews,overall_return_prob_product,is_returned
0,0,1,72.126503,3.330133,0.211765,0.864706,0.202666,1.000000,0.048002,0.0,0.038251,0.032484,will_be_predicted
1,0,1,89.922159,4.446509,0.159091,0.886364,0.214756,1.000000,0.049145,0.0,0.147989,0.020519,will_be_predicted
2,0,1,79.813529,4.327934,0.218487,0.731092,0.202961,0.991597,0.055154,0.0,0.079365,0.014656,will_be_predicted
3,0,1,54.640780,3.002397,0.159696,0.787072,0.149364,1.000000,0.057721,0.0,0.104369,0.032484,will_be_predicted
4,0,1,65.268633,2.992710,0.173585,0.792453,0.149895,1.000000,0.048013,0.0,0.104167,0.032484,will_be_predicted
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7466,0,0,142.164107,4.872519,0.098214,0.767857,0.148564,1.000000,0.033868,0.0,0.159091,0.032484,will_be_predicted
7467,0,0,109.249958,2.739447,0.125000,0.663136,0.119912,1.000000,0.026313,0.0,0.128008,0.032484,will_be_predicted
7468,0,1,146.338667,7.691000,0.266667,1.000000,0.332255,1.000000,0.050333,0.0,0.091743,0.560377,will_be_predicted
7469,0,1,32.243333,3.090134,0.303704,0.807407,0.193715,0.992593,0.096521,0.0,0.038961,0.032484,will_be_predicted
7470,0,1,72.126503,3.330133,0.211765,0.864706,0.202666,1.000000,0.048002,0.0,0.038251,0.032484,will_be_predicted

In [138]:
X = test_joined_final_without_ids.iloc[:, :-1].values
y = test_joined_final_without_ids.iloc[:, -1].values

In [139]:
scaler_for_pred = StandardScaler()
X = scaler_for_pred.fit_transform(X)
X = scaler_for_pred.transform(X)

In [140]:
len(X)

7471

In [141]:
y_pred = classifier.predict(X)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [142]:
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [143]:
len(y_pred)

7471

In [144]:
sum(y_pred)/7471

0.008164904296613573

In [145]:
gc.collect()

200

In [146]:
test_ids = test_joined_final[['user_id','product_content_id','order_parent_id']]

In [147]:
test_joined_final

,user_id,product_content_id,order_parent_id,is_returned,Bay,Bayan,discounted_price,ship_cost,coupon_used,is_discounted,promotion_percent,is_shipcost_incurred,shipping_percent,return_prob_from_answers,return_prob_from_reviews,overall_return_prob_product
0,18115,87073974,726348863,will_be_predicted,0,1,72.126503,3.330133,0.211765,0.864706,0.202666,1.000000,0.048002,0.0,0.038251,0.032484
1,27588,118753298,723169934,will_be_predicted,0,1,89.922159,4.446509,0.159091,0.886364,0.214756,1.000000,0.049145,0.0,0.147989,0.020519
2,29165,35699988,724122443,will_be_predicted,0,1,79.813529,4.327934,0.218487,0.731092,0.202961,0.991597,0.055154,0.0,0.079365,0.014656
3,29969,5893187,722342150,will_be_predicted,0,1,54.640780,3.002397,0.159696,0.787072,0.149364,1.000000,0.057721,0.0,0.104369,0.032484
4,35107,93897418,723421057,will_be_predicted,0,1,65.268633,2.992710,0.173585,0.792453,0.149895,1.000000,0.048013,0.0,0.104167,0.032484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7466,71083899,100019570,728638514,will_be_predicted,0,0,142.164107,4.872519,0.098214,0.767857,0.148564,1.000000,0.033868,0.0,0.159091,0.032484
7467,71106534,35624085,725372928,will_be_predicted,0,0,109.249958,2.739447,0.125000,0.663136,0.119912,1.000000,0.026313,0.0,0.128008,0.032484
7468,71115350,94438742,725291348,will_be_predicted,0,1,146.338667,7.691000,0.266667,1.000000,0.332255,1.000000,0.050333,0.0,0.091743,0.560377
7469,71115350,100017676,725291348,will_be_predicted,0,1,32.243333,3.090134,0.303704,0.807407,0.193715,0.992593,0.096521,0.0,0.038961,0.032484
7470,71160557,87073974,726377172,will_be_predicted,0,1,72.126503,3.330133,0.211765,0.864706,0.202666,1.000000,0.048002,0.0,0.038251,0.032484

In [148]:
test_ids

       user_id  product_content_id  order_parent_id
0        18115            87073974        726348863
1        27588           118753298        723169934
2        29165            35699988        724122443
3        29969             5893187        722342150
4        35107            93897418        723421057
...        ...                 ...              ...
7466  71083899           100019570        728638514
7467  71106534            35624085        725372928
7468  71115350            94438742        725291348
7469  71115350           100017676        725291348
7470  71160557            87073974        726377172

[7471 rows x 3 columns]

In [149]:
test_ids['is_returned'] = y_pred

<ipython-input-149-e551a14b1c99>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_ids['is_returned'] = y_pred

In [150]:
test_ids

       user_id  product_content_id  order_parent_id  is_returned
0        18115            87073974        726348863          0.0
1        27588           118753298        723169934          0.0
2        29165            35699988        724122443          0.0
3        29969             5893187        722342150          0.0
4        35107            93897418        723421057          0.0
...        ...                 ...              ...          ...
7466  71083899           100019570        728638514          0.0
7467  71106534            35624085        725372928          0.0
7468  71115350            94438742        725291348          0.0
7469  71115350           100017676        725291348          0.0
7470  71160557            87073974        726377172          0.0

[7471 rows x 4 columns]

In [151]:
pd.set_option("display.max_columns", None)

In [152]:
test_ids.is_returned.sum()/7471

0.008164904296613573

In [118]:
#SUBMISSION TEMPLATE
test_ids['id'] = test_ids['user_id'].map(str) + '|' + test_ids['product_content_id'].map(str) + '|' + test_ids['order_parent_id'].map(str)

test_ids = test_ids.drop(['user_id','product_content_id','order_parent_id'],axis=1)
test_ids = test_ids[['id','is_returned']]

test_ids = test_ids.rename({'is_returned':'expected'},axis=1)

test_ids.expected = test_ids.expected.astype(int)

test_ids.to_csv(file_path+'submission5.csv',index=False)

<ipython-input-118-3967364c4699>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_ids['id'] = test_ids['user_id'].map(str) + '|' + test_ids['product_content_id'].map(str) + '|' + test_ids['order_parent_id'].map(str)

In [54]:
#SUBMISSION TEMPLATE
test_ids['id'] = test_ids['user_id'].map(str) + '|' + test_ids['product_content_id'].map(str) + '|' + test_ids['order_parent_id'].map(str)

<ipython-input-54-c51d062d633f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_ids['id'] = test_ids['user_id'].map(str) + '|' + test_ids['product_content_id'].map(str) + '|' + test_ids['order_parent_id'].map(str)

In [58]:
test_ids = test_ids.drop(['user_id','product_content_id','order_parent_id'],axis=1)
test_ids = test_ids[['id','is_returned']]

In [59]:
test_ids.head(2)

                          id  is_returned
0   18115|87073974|726348863          1.0
1  27588|118753298|723169934          0.0

In [61]:
gc.collect()

22

In [63]:
test_ids = test_ids.rename({'is_returned':'expected'},axis=1)

In [65]:
test_ids.expected = test_ids.expected.astype(bool)

In [68]:
test_ids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7471 entries, 0 to 7470
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7471 non-null   object
 1   expected  7471 non-null   bool
dtypes: bool(1), object(1)
memory usage: 65.8+ KB

In [69]:
test_ids.to_csv(file_path+'submission1.csv',index=False)

In [70]:
test_ids.expected = test_ids.expected.astype(int)

In [71]:
test_ids

                                id  expected
0         18115|87073974|726348863         1
1        27588|118753298|723169934         0
2         29165|35699988|724122443         0
3          29969|5893187|722342150         0
4         35107|93897418|723421057         0
...                            ...       ...
7466  71083899|100019570|728638514         0
7467   71106534|35624085|725372928         0
7468   71115350|94438742|725291348         0
7469  71115350|100017676|725291348         0
7470   71160557|87073974|726377172         1

[7471 rows x 2 columns]

In [72]:
test_ids.to_csv(file_path+'submission2.csv',index=False)

In [73]:
data2

,Bay,Bayan,discounted_price,ship_cost,coupon_used,is_discounted,promotion_percent,is_shipcost_incurred,shipping_percent,return_prob_from_answers,return_prob_from_reviews,overall_return_prob_product,is_returned
0,0,1,51.94,8.880,0,1,0.349937,1,0.170966,0.0,0.000000,0.025306,0.0
1,0,1,59.97,9.400,0,1,0.538515,1,0.156745,0.0,0.047619,0.012821,0.0
2,0,1,49.99,10.670,0,1,0.166694,1,0.213443,0.0,0.000000,0.273525,0.0
3,0,1,49.90,10.670,0,0,0.000000,1,0.213828,0.0,0.000000,0.027232,0.0
4,0,1,71.99,9.400,0,1,0.200022,1,0.130574,0.0,0.083333,0.032484,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10772617,0,1,71.99,11.330,0,1,0.640032,1,0.157383,0.0,0.040650,0.010932,0.0
10772618,0,1,85.58,2.098,0,1,0.643342,1,0.024515,0.0,0.037037,0.012821,0.0
10772619,0,1,75.98,2.098,0,1,0.650038,1,0.027613,0.0,0.000000,0.012821,0.0
10772620,0,1,69.73,10.490,0,1,0.650038,1,0.150437,0.0,0.000000,0.016131,0.0
10772621,0,1,75.98,2.098,0,1,0.650038,1,0.027613,0.0,0.000000,0.012821,0.0

In [80]:
#data = pd.read_csv(file_path + 'main_data_final.csv')

In [77]:
data

,is_elite_user,discounted_price,ship_cost,is_wallet_trx,is_saved_card_trx,coupon_used,is_different_sizes,is_discounted,promotion_percent,is_shipcost_incurred,shipping_percent,Erkek,GenderlessItem,Kadın,Kadın_Kız,Unisex,Altın,Bej,Beyaz,Bordo,Ekru,Gri,Gümüş,Haki,Kahverengi,Kırmızı,Lacivert,Mavi,Metalik,Mor,Multicolor,Pembe,Sarı,Siyah,Turkuaz,Turuncu,Yeşil,return_prob_from_answers,return_prob_from_reviews,Bay,Bayan,overall_return_prob_product,is_returned
0,0,51.94,8.880,0,1,0,0,1,0.349937,1,0.170966,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.000000,0,1,0.025306,0.0
1,0,59.97,9.400,0,1,0,0,1,0.538515,1,0.156745,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.0,0.047619,0,1,0.012821,0.0
2,0,49.99,10.670,0,1,0,0,1,0.166694,1,0.213443,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.000000,0,1,0.273525,0.0
3,0,49.90,10.670,0,1,0,0,0,0.000000,1,0.213828,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0.0,0.000000,0,1,0.027232,0.0
4,1,71.99,9.400,0,0,0,0,1,0.200022,1,0.130574,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.083333,0,1,0.032484,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10772617,0,71.99,11.330,1,0,0,1,1,0.640032,1,0.157383,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.040650,0,1,0.010932,0.0
10772618,0,85.58,2.098,1,0,0,1,1,0.643342,1,0.024515,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.0,0.037037,0,1,0.012821,0.0
10772619,0,75.98,2.098,1,0,0,1,1,0.650038,1,0.027613,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.000000,0,1,0.012821,0.0
10772620,0,69.73,10.490,1,0,0,1,1,0.650038,1,0.150437,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.000000,0,1,0.016131,0.0
10772621,0,75.98,2.098,1,0,0,1,1,0.650038,1,0.027613,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.000000,0,1,0.012821,0.0

In [76]:
pd.set_option("display.max_columns", None)